import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "@/context";
import { Provider } from "react-redux";
import store from "@/lib/store";
import ClientProvider from "./clientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <AppWrapper>{children}</AppWrapper>
          </ClientProvider>
      </body>
    </html>
  );
}
